### ISSUE TITLE
Issue on page /03.html

### ISSUE THREAD

**Issue by PhilClarkPhD** [Mark-Kramer/Case-Studies-Python#15]
*Im really enjoying this book! But I came across something that has me confused On page 3, we have:*

x = EEG
xf = rfft(x - x.mean()).real

*And the next code block reads:*

Sxx = 2 * dt ** 2 / T * xf * xf.conj()
....

*But if we perform np.real on xf, then multiplying xf by its conjugate (xf.conj()) gives the same result as squaring xf, which is not equivalent to multiplying an array of complex numbers by its complex conjugate.*

*To illustrate, just below this code you have another example, written somewhat differently:*

xf = rfft(x - x.mean())
Sxx = (2 * dt ** 2 / T * ( xf * xf.conj() ) ).real
....

*When I plug the same array x into each of these, they do not return the same Sxx result. My example is below.*

xf = rfft(x-x.mean()).real
Sxx = 2 * dt ** 2 / T * xf * xf.conj()

xf2 = rfft(x - x.mean())
Sxx2 = (2 * dt ** 2 / T * ( xf2 * xf2.conj() ) ).real

*This evaluates to false*
np.all(Sxx==Sxx2)

*Thanks again for producing this work, it has been tremendously helpful to me!*

**Comment by eschlaf2** [comment]
Great catch @PhilClarkPhD! Glad to hear you are enjoying the book!
