### ISSUE TITLE
Binder file won't run?

### ISSUE THREAD

**Issue by pjkohler** [Mark-Kramer/Case-Studies-Python#16]
Hello, 

thanks for the excellent resource. I am trying to run the Binder version of the notebooks:

https://mybinder.org/v2/gh/Mark-Kramer/Case-Studies-Python/master

but it fails to start. I have tried both firefox and chrome. I am totally unfamiliar with Binder, so difficult to debug. 

Best,

Peter

**Comment by pjkohler** [comment]
Seems to be working now - thanks!

**Comment by Mark-Kramer** [comment]
Great, thank you. I find in practice that launching on Binder can take a few attempts.
