### ISSUE TITLE
Coherence code_square roots are missing from the two denominator terms

### ISSUE THREAD

**Issue by chrihoni** [Mark-Kramer/Case-Studies-Python#18]
To estimate spike-field coherence  between two time series x and y the section "Mathematical description of spike-field coherence"   states that the magnitude of trial averaged cross spectrum of x and y  is divided by the square root of the trial averaged x and y spectra.	 
	
In the python code, coherence is calculated as:  cohr = real(SYN*conj(SYN)) / SYY / SNN. 
**When comparing the "mathematical formula" in the text to  the "code formula"  it seems that the code formula lacks the square roots in the denominator and the numerator takes the real part of the "conjugated product" (which is basically the squared absolute value of the cross spectrum?!).** Hence it seems that the "code formula" is the squared "mathematical formula"?! 
	
If the "mathematical formula" in the text is correct, would the code formula be then as follows?

cohr = sqrt(real(SYN*conj(SYN))) / sqrt(SYY) / sqrt(SNN)

or 

cohr = abs(SYN) / sqrt(SYY) / sqrt(SNN)

?

Best,
Christoph

**Comment by eschlaf2** [comment]
Hi Christoph, you're absolutely right. We've updated the code formula to read `cohr = abs(SYN) / sqrt(SYY) / sqrt(SNN)`. Thanks for the edit!
