### ISSUE TITLE
FitzHugh-Nagumo /HH.html

### ISSUE THREAD

**Issue by vivekhsridhar** [Mark-Kramer/Case-Studies-Python#19]
Dear Mark,

I'm really enjoying your video lectures along with code on the neural spike train analysis! I've followed the video lectures from the Integrate-and-fire model till the end of the Hodgkin-Huxley model. At the end of this video, you say that we will move on to the FitzHugh-Nagumo model next. But I don't find this video or code online. I was wondering if you could post this / guide me to a link where I can find this?

Thanks so much for this valuable resource!

Vivek

**Comment by Mark-Kramer** [comment]
I can't find the video, but I've attached the lecture notes. In it, we use the software [XPPAUT](http://www.scholarpedia.org/article/XPPAUT). I hope that's helpful.

[SAMSI_Lecture_3.pdf](https://github.com/Mark-Kramer/Case-Studies-Python/files/10315866/SAMSI_Lecture_3.pdf)

**Comment by vivekhsridhar** [comment]
Dear Mark,

This is definitely helpful. I would just like to say that you teach very well and watching those videos helped me assimilate the material rather quickly.

Thank you.

Vivek
