### ISSUE TITLE
Issue on page /08.html

### ISSUE THREAD

**Issue by gregsadetsky** [Mark-Kramer/Case-Studies-Python#20]
Congrats and thanks for making this resource available!

Very small thing -- on https://mark-kramer.github.io/Case-Studies-Python/08.html#computing-autocorrelations-for-the-increments , right after "the closer the value is to", instead of seeing "±" (i.e. the plus minus symbol), what appears on the page is literally `$\pm$` . See below for screenshot:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/1017304/210876964-2ed038b3-d333-475a-968d-91eaebec58b6.png">

Cheers

**Comment by gregsadetsky** [comment]
Looking for the `$` character on the same page, I also see that in

https://mark-kramer.github.io/Case-Studies-Python/08.html#appendix-spike-count-mean-and-variance-for-a-poisson-process

the formulas that appear right before "where again we’ve used the definition of" have spurious dollar signs (i.e. `$`) on both sides of the formula/equation block:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1017304/210877579-2fd1e61c-daa1-42fb-ad77-4ab506cd2984.png">

Thanks again

**Comment by Mark-Kramer** [comment]
Both no resolved and posted to site. Thank you!
